### ISSUE TITLE
Autoreconnect after failure (handle 504 Gateway Time-out)

### ISSUE THREAD

**Issue by Defozo** [Ullink/simple-slack-api#83] opened 2016-06-03 23:43 UTC
After some long time of properly working... suddenly...
http://pastebin.com/4EkEUzQP
App crashes.

**Comment by freesoft** [comment] 2016-06-24 04:11
The line 278 of com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl as of today is

```
LOGGER.debug("retrieved websocket URL : " + wssurl);
```

and there is noting NullPointerException can be occur. You might need to specify which release you are using.

**Comment by gluck** [comment] 2016-07-12 09:52
sounds like a duplicate of #108 which has more info :smile:

**Closed by gluck** 2016-07-12 09:52 UTC
